
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v4.2  Build: December 11th, 2015
-- SQL Server 2000/2005/2008/2008R2/2012/Express DDL Script generated from project: Enio
-- Project filename: C:\Users\ninja\Documents\GitHub\NinjaSoftware.EnioNg\Enio.llblgenproj
-- Script generated on: 28-ožu-2016 07:21.33
--
-- This is a Create script for creating a NEW data model. If you want DDL SQL for updating an existing model,
-- please create an Update script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime. Schemas aren't dropped in the DROP section.
--
--      >>>>> WARNING <<<<<
--      This is a CREATE script, with DROP statements for the existing tables, foreign keys and other constraints
--      This means that existing tables, data, constraints and other elements in the catalog/schemas addressed
--      are deleted. Use this Create script only to create new schemas with tables/constraints and other elements.
--
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- DROP statements for existing elements. 
-- ###############################################################################################################
-- DROP statements for dropping existing elements with the same names as the ones created are commented out below. 
-- If you want to enable these statements for DROPping the existing elements first (which will remove all the data
-- in these existing elements), uncomment these statements by removing the two comment markers /* and */

-- Remove the comment marker on the NEXT line to enable DROP statements to remove existing elements
/* 

USE [EnioNg]
GO
*/
-- Remove the comment marker on the PREVIOUS line to enable DROP statements to remove existing elements

-- ###############################################################################################################
-- Create statements for catalogs, schemas, tables and sequences
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'EnioNg'
-- ----------------------------------------------------------------------------------------------------------------

USE master
GO
CREATE DATABASE [EnioNg] /* ON PRIMARY (NAME=EnioNg_dat, FILENAME='c:\mycatalogs\EnioNg.mdf', SIZE=10MB) */
GO


USE [EnioNg]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

-- -------[ Tables ]-----------------------------------------------------------------------------------------------

CREATE TABLE [dbo].[Artikl] 
(
	[ArtiklId] [bigint] NOT NULL, 
	[Cijena] [decimal] (10, 2) NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[IsActive] [bit] NOT NULL, 
	[Jm] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Naziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[PdvId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[AuditInfo] 
(
	[ActionDateTime] [datetime] NOT NULL, 
	[AuditInfoActionTypeId] [bigint] NOT NULL, 
	[AuditInfoId] [bigint] NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[EntityId] [bigint] NOT NULL, 
	[JsonData] [nvarchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[PrimaryKeyValue] [bigint] NOT NULL, 
	[UserId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[AuditInfoActionTypeRo] 
(
	[AuditInfoActionTypeId] [bigint] NOT NULL, 
	[Code] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Name] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Brojac] 
(
	[BrojacId] [bigint] NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Godina] [smallint] NOT NULL, 
	[Naziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[SlijedeciBroj] [int] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Config] 
(
	[Adresa] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[AktivnaGodina] [smallint] NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[ConfigId] [bigint] NOT NULL, 
	[Mjesto] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Naziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Oib] [nvarchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Zr] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[EntityRo] 
(
	[Code] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[EntityId] [bigint] NOT NULL, 
	[Name] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Error] 
(
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[ErrorDateTime] [datetime] NOT NULL, 
	[ErrorId] [bigint] NOT NULL, 
	[Message] [nvarchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[ParentErrorId] [bigint] NULL, 
	[StackTrace] [nvarchar] (MAX) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Partner] 
(
	[Adresa] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[IsActive] [bit] NOT NULL, 
	[Mjesto] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Naziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Oib] [nvarchar] (11) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[PartnerId] [bigint] NOT NULL, 
	[Posta] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Valuta] [smallint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Pdv] 
(
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Naziv] [nvarchar] (128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[PdvId] [bigint] NOT NULL, 
	[Stopa] [decimal] (4, 2) NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RacunGlava] 
(
	[BrojRacuna] [int] NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Datum] [datetime] NOT NULL, 
	[Godina] [smallint] NOT NULL, 
	[JePdvRacun] [bit] NOT NULL, 
	[MjestoRadaAdresa] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[MjestoRadaNaziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[PartnerId] [bigint] NOT NULL, 
	[RacunGlavaId] [bigint] NOT NULL, 
	[StatusId] [bigint] NOT NULL, 
	[TarifaId] [bigint] NOT NULL, 
	[TarifaStopa] [decimal] (5, 2) NOT NULL, 
	[Valuta] [smallint] NOT NULL, 
	[Vrijeme] [nvarchar] (10) COLLATE SQL_Latin1_General_CP1_CI_AS NULL, 
	[Zaglavlje] [nvarchar] (1024) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RacunStavka] 
(
	[ArtiklId] [bigint] NOT NULL, 
	[Cijena] [decimal] (10, 2) NOT NULL, 
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Iznos] [decimal] (10, 2) NOT NULL, 
	[Kolicina] [decimal] (8, 2) NOT NULL, 
	[PdvIznos] [decimal] (10, 2) NOT NULL, 
	[PdvPosto] [decimal] (4, 2) NOT NULL, 
	[Pozicija] [smallint] NOT NULL, 
	[RacunGlavaId] [bigint] NOT NULL, 
	[RacunStavkaId] [bigint] NOT NULL, 
	[TarifaIznos] [decimal] (10, 2) NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[RoleRo] 
(
	[Code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[RoleId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[StatusRo] 
(
	[Code] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Name] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[StatusId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[Tarifa] 
(
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[IsActive] [bit] NOT NULL, 
	[Naziv] [nvarchar] (100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Stopa] [decimal] (5, 2) NOT NULL, 
	[TarifaId] [bigint] NOT NULL 
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[User] 
(
	[ConcurrencyGuid] [nvarchar] (50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[Password] [nvarchar] (256) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, 
	[RoleId] [bigint] NOT NULL, 
	[UserId] [bigint] NOT NULL, 
	[Username] [nvarchar] (20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL 
) ON [PRIMARY]
GO
-- -------[ Sequences ]--------------------------------------------------------------------------------------------

CREATE SEQUENCE [dbo].[GenericSequence] START WITH 1 INCREMENT BY 1 NO MAXVALUE NO CYCLE; 
GO

-- ###############################################################################################################
-- Create statements for Primary key constraints, Foreign key constraints, Unique constraints and Default Values
-- ###############################################################################################################
-- ----------------------------------------------------------------------------------------------------------------
-- Catalog 'EnioNg'
-- ----------------------------------------------------------------------------------------------------------------

USE [EnioNg]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Primary Key constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Artikl] WITH NOCHECK 
	ADD CONSTRAINT [PK_9c803004f50ba5ffc2cbbce7fd6] PRIMARY KEY CLUSTERED 
	( 
		[ArtiklId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[AuditInfo] WITH NOCHECK 
	ADD CONSTRAINT [PK_6053f4d4730b680d7f95a95a466] PRIMARY KEY CLUSTERED 
	( 
		[AuditInfoId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[AuditInfoActionTypeRo] WITH NOCHECK 
	ADD CONSTRAINT [PK_c5cb8d84eee9efaed9cdddda9be] PRIMARY KEY CLUSTERED 
	( 
		[AuditInfoActionTypeId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Brojac] WITH NOCHECK 
	ADD CONSTRAINT [PK_68a48f24c87b2f9b701749eaaf1] PRIMARY KEY CLUSTERED 
	( 
		[BrojacId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Config] WITH NOCHECK 
	ADD CONSTRAINT [PK_6e20f0e4604987af6ca9d11d0eb] PRIMARY KEY CLUSTERED 
	( 
		[ConfigId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[EntityRo] WITH NOCHECK 
	ADD CONSTRAINT [PK_742767646238675b9e8910a79b2] PRIMARY KEY CLUSTERED 
	( 
		[EntityId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Error] WITH NOCHECK 
	ADD CONSTRAINT [PK_1a3a46e492a86486dfe55fede0e] PRIMARY KEY CLUSTERED 
	( 
		[ErrorId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Partner] WITH NOCHECK 
	ADD CONSTRAINT [PK_4b068ed45d1a4b9f5c82a158472] PRIMARY KEY CLUSTERED 
	( 
		[PartnerId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Pdv] WITH NOCHECK 
	ADD CONSTRAINT [PK_47ccc66493699ae147800802b31] PRIMARY KEY CLUSTERED 
	( 
		[PdvId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RacunGlava] WITH NOCHECK 
	ADD CONSTRAINT [PK_da97b3b478ab0db3c71383fe2f5] PRIMARY KEY CLUSTERED 
	( 
		[RacunGlavaId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RacunStavka] WITH NOCHECK 
	ADD CONSTRAINT [PK_f1f70f2432db7e03eb88d5c8eed] PRIMARY KEY CLUSTERED 
	( 
		[RacunStavkaId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[RoleRo] WITH NOCHECK 
	ADD CONSTRAINT [PK_f26c6ef4763b3ae3d5a80c08199] PRIMARY KEY CLUSTERED 
	( 
		[RoleId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[StatusRo] WITH NOCHECK 
	ADD CONSTRAINT [PK_dc99234402ab2001ace09edd545] PRIMARY KEY CLUSTERED 
	( 
		[StatusId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Tarifa] WITH NOCHECK 
	ADD CONSTRAINT [PK_55472c54ce1affd1805f744016f] PRIMARY KEY CLUSTERED 
	( 
		[TarifaId] 
	) ON [PRIMARY]
GO

ALTER TABLE [dbo].[User] WITH NOCHECK 
	ADD CONSTRAINT [PK_4f2669a4ba7b6f38984e55d0e7a] PRIMARY KEY CLUSTERED 
	( 
		[UserId] 
	) ON [PRIMARY]
GO
-- ----------------------------------------------------------------------------------------------------------------
-- Unique constraints for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- Default values for schema 'dbo'
-- ----------------------------------------------------------------------------------------------------------------
-- ----------------------------------------------------------------------------------------------------------------
-- All foreign Key constraints
-- ----------------------------------------------------------------------------------------------------------------

ALTER TABLE [dbo].[Artikl] 
	ADD CONSTRAINT [FK_641dca045d0bd173ad6b6bbf0f1] FOREIGN KEY
	(
		[PdvId] 
	)
	REFERENCES [dbo].[Pdv]
	(
		[PdvId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[AuditInfo] 
	ADD CONSTRAINT [FK_7adf5f54794b92ee8dbbf2de480] FOREIGN KEY
	(
		[UserId] 
	)
	REFERENCES [dbo].[User]
	(
		[UserId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[AuditInfo] 
	ADD CONSTRAINT [FK_98f8c634e618ff0289ebfdccbc9] FOREIGN KEY
	(
		[EntityId] 
	)
	REFERENCES [dbo].[EntityRo]
	(
		[EntityId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[AuditInfo] 
	ADD CONSTRAINT [FK_aac353f4b949cafe66dc9996c58] FOREIGN KEY
	(
		[AuditInfoActionTypeId] 
	)
	REFERENCES [dbo].[AuditInfoActionTypeRo]
	(
		[AuditInfoActionTypeId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Error] 
	ADD CONSTRAINT [FK_ff41a304a119b8a47a7f448681e] FOREIGN KEY
	(
		[ParentErrorId] 
	)
	REFERENCES [dbo].[Error]
	(
		[ErrorId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RacunGlava] 
	ADD CONSTRAINT [FK_1a7fe194f72a6d752d98820bb15] FOREIGN KEY
	(
		[StatusId] 
	)
	REFERENCES [dbo].[StatusRo]
	(
		[StatusId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RacunGlava] 
	ADD CONSTRAINT [FK_915476249258bb0eda968f27354] FOREIGN KEY
	(
		[TarifaId] 
	)
	REFERENCES [dbo].[Tarifa]
	(
		[TarifaId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RacunGlava] 
	ADD CONSTRAINT [FK_dc2573043ccbffae8edb54fba1c] FOREIGN KEY
	(
		[PartnerId] 
	)
	REFERENCES [dbo].[Partner]
	(
		[PartnerId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RacunStavka] 
	ADD CONSTRAINT [FK_04416ac49618ddd7bea2492ae7b] FOREIGN KEY
	(
		[RacunGlavaId] 
	)
	REFERENCES [dbo].[RacunGlava]
	(
		[RacunGlavaId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RacunStavka] 
	ADD CONSTRAINT [FK_04eb9704b6e926ee09dbd1f5b03] FOREIGN KEY
	(
		[ArtiklId] 
	)
	REFERENCES [dbo].[Artikl]
	(
		[ArtiklId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[User] 
	ADD CONSTRAINT [FK_78b50b94da190966eb5c0de1b9f] FOREIGN KEY
	(
		[RoleId] 
	)
	REFERENCES [dbo].[RoleRo]
	(
		[RoleId] 
	)
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
GO

