
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v4.2  Build: December 11th, 2015
-- SQL Server 2000/2005/2008/2008R2/2012/Express DDL Script generated from project: Enio
-- Project filename: C:\Users\ninja\Documents\GitHub\NinjaSoftware.EnioNg\Enio.llblgenproj
-- Script generated on: 02-stu-2017 09:29.08
--
-- This is an Update script for updating an existing data model to a newer version. If you want DDL SQL for a new model,
-- please create a Create script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime.
--
-- Please run the scripts in the right order, use the timestamp in the filename and inside this script for that.
-- This script might need adjustment in some statements. You should consider this script as a starting point for
-- upgrading the existing data model.
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- Drop constraints referring to elements which are changed in this script (constraints are recreated later on)
-- ###############################################################################################################

USE [EnioNg]
GO

ALTER TABLE [dbo].[Firma] DROP CONSTRAINT [PK_dc048334f91a208a531bcb2db7f]
GO

-- ###############################################################################################################
-- Rename statements
-- ###############################################################################################################

USE [EnioNg]
GO

-- ###############################################################################################################
-- DROP statements for elements no longer needed or replaced elements.
-- ###############################################################################################################

USE [EnioNg]
GO

-- ###############################################################################################################
-- ADD statements for new elements (except FK/UC)
-- ###############################################################################################################

USE [EnioNg]
GO

-- ###############################################################################################################
-- ALTER statements for table fields and ADD statements for new primary key constraints
-- ###############################################################################################################

USE [EnioNg]
GO

ALTER TABLE [dbo].[Firma] WITH NOCHECK 
	ADD CONSTRAINT [PK_dc048334f91a208a531bcb2db7f] PRIMARY KEY CLUSTERED 
	( 
		[FirmaId] 
	) ON [PRIMARY]
GO

-- ###############################################################################################################
-- ADD statements for new foreign key constraints, unique constraints and default values
-- ###############################################################################################################

USE [EnioNg]
GO

ALTER TABLE [dbo].[Artikl] 
	ADD CONSTRAINT [FK_a91065c48b5b1270a5e99010cc5] FOREIGN KEY
	(
		[FirmaId] 
	)
	REFERENCES [dbo].[Firma]
	(
		[FirmaId] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Brojac] 
	ADD CONSTRAINT [FK_0a47816464d84da2a2ba1df8b7d] FOREIGN KEY
	(
		[FirmaId] 
	)
	REFERENCES [dbo].[Firma]
	(
		[FirmaId] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Config] 
	ADD CONSTRAINT [FK_171c18f4473abe5aa32d2a62b3b] FOREIGN KEY
	(
		[FirmaId] 
	)
	REFERENCES [dbo].[Firma]
	(
		[FirmaId] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Partner] 
	ADD CONSTRAINT [FK_8185c1440e2a279aefb94d1ab69] FOREIGN KEY
	(
		[FirmaId] 
	)
	REFERENCES [dbo].[Firma]
	(
		[FirmaId] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Pdv] 
	ADD CONSTRAINT [FK_b6550d04f60807015672af83808] FOREIGN KEY
	(
		[FirmaId] 
	)
	REFERENCES [dbo].[Firma]
	(
		[FirmaId] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[RacunGlava] 
	ADD CONSTRAINT [FK_ce441ba48fda4d3bde655d14ac8] FOREIGN KEY
	(
		[FirmaId] 
	)
	REFERENCES [dbo].[Firma]
	(
		[FirmaId] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[Tarifa] 
	ADD CONSTRAINT [FK_eeee1e542688d56b261d6658b1a] FOREIGN KEY
	(
		[FirmaId] 
	)
	REFERENCES [dbo].[Firma]
	(
		[FirmaId] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


ALTER TABLE [dbo].[User] 
	ADD CONSTRAINT [FK_a9d8edd41e1a0162cc78a0701c1] FOREIGN KEY
	(
		[FirmaId] 
	)
	REFERENCES [dbo].[Firma]
	(
		[FirmaId] 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION
GO


