
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v4.0  Build: May 15th, 2013
-- PostgreSql 7.x/8.x/9.x DDL Script generated from project: Enio
-- Project filename: G:\Documents\Visual Studio 2010\Projects\NinjaSoftware.EnioNg\Enio.llblgenproj
-- Script generated on: 17-lis-2014 18:55.52
--
-- This is an Update script for updating an existing data model to a newer version. If you want DDL SQL for a new model,
-- please create a Create script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime.
--
-- Please run the scripts in the right order, use the timestamp in the filename and inside this script for that.
-- This script might need adjustment in some statements. You should consider this script as a starting point for
-- upgrading the existing data model.
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- Drop constraints referring to elements which are changed in this script (constraints are recreated later on)
-- ###############################################################################################################

-- ###############################################################################################################
-- Rename statements
-- ###############################################################################################################

-- ###############################################################################################################
-- DROP statements for elements no longer needed or replaced elements.
-- ###############################################################################################################

-- ###############################################################################################################
-- ADD statements for new elements (except FK/UC)
-- ###############################################################################################################

ALTER TABLE "public"."RacunGlava" 
	ADD COLUMN "JePdvRacun" bool NOT NULL;

ALTER TABLE "public"."RacunGlava" 
	ADD COLUMN "Zaglavlje" varchar(1024) NULL;

-- ###############################################################################################################
-- ALTER statements for table fields and ADD statements for new primary key constraints
-- ###############################################################################################################

-- ###############################################################################################################
-- ADD statements for new foreign key constraints and unique constraints
-- ###############################################################################################################

