
-- ----------------------------------------------------------------------------------------------------------------
-- Generated by LLBLGen Pro v4.2  Build: December 11th, 2015
-- PostgreSql 7.x/8.x/9.x DDL Script generated from project: Enio
-- Project filename: C:\Users\ninja\Documents\GitHub\NinjaSoftware.EnioNg\Enio.llblgenproj
-- Script generated on: 02-stu-2017 09:29.08
--
-- This is an Update script for updating an existing data model to a newer version. If you want DDL SQL for a new model,
-- please create a Create script instead. 
--
-- This script might create schemas, which requires you to assign a proper user to the schema. Adjust the CREATE SCHEMA
-- statements below, if any, to avoid errors at runtime.
--
-- Please run the scripts in the right order, use the timestamp in the filename and inside this script for that.
-- This script might need adjustment in some statements. You should consider this script as a starting point for
-- upgrading the existing data model.
-- ----------------------------------------------------------------------------------------------------------------
-- ###############################################################################################################
-- Drop constraints referring to elements which are changed in this script (constraints are recreated later on)
-- ###############################################################################################################

ALTER TABLE "public"."Firma" DROP CONSTRAINT "PK_7343ec14f8194191496c9e7cd04";

-- ###############################################################################################################
-- Rename statements
-- ###############################################################################################################

-- ###############################################################################################################
-- DROP statements for elements no longer needed or replaced elements.
-- ###############################################################################################################

-- ###############################################################################################################
-- ADD statements for new elements (except FK/UC)
-- ###############################################################################################################

-- ###############################################################################################################
-- ALTER statements for table fields and ADD statements for new primary key constraints
-- ###############################################################################################################

ALTER TABLE "public"."Firma"
	ADD CONSTRAINT "PK_7343ec14f8194191496c9e7cd04" PRIMARY KEY
	( 
		"FirmaId" 
	);

-- ###############################################################################################################
-- ADD statements for new foreign key constraints, unique constraints and default values
-- ###############################################################################################################

ALTER TABLE "public"."Artikl" 
	ADD CONSTRAINT "FK_cc345e9404981dc0b021c4cb3db" FOREIGN KEY
	(
		"FirmaId" 
	)
	REFERENCES "public"."Firma"
	(
		"FirmaId" 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


ALTER TABLE "public"."Brojac" 
	ADD CONSTRAINT "FK_84f10ff472c901e71e1fe13d6d0" FOREIGN KEY
	(
		"FirmaId" 
	)
	REFERENCES "public"."Firma"
	(
		"FirmaId" 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


ALTER TABLE "public"."Config" 
	ADD CONSTRAINT "FK_8787a514ce6bbc4de825762153f" FOREIGN KEY
	(
		"FirmaId" 
	)
	REFERENCES "public"."Firma"
	(
		"FirmaId" 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


ALTER TABLE "public"."Partner" 
	ADD CONSTRAINT "FK_867997e40bfafc662f718c4a14a" FOREIGN KEY
	(
		"FirmaId" 
	)
	REFERENCES "public"."Firma"
	(
		"FirmaId" 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


ALTER TABLE "public"."Pdv" 
	ADD CONSTRAINT "FK_78998144e92933effcf226e67bc" FOREIGN KEY
	(
		"FirmaId" 
	)
	REFERENCES "public"."Firma"
	(
		"FirmaId" 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


ALTER TABLE "public"."RacunGlava" 
	ADD CONSTRAINT "FK_bac24104346a080da3b813d65d1" FOREIGN KEY
	(
		"FirmaId" 
	)
	REFERENCES "public"."Firma"
	(
		"FirmaId" 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


ALTER TABLE "public"."Tarifa" 
	ADD CONSTRAINT "FK_f920fcc43cea984ddbfcb566707" FOREIGN KEY
	(
		"FirmaId" 
	)
	REFERENCES "public"."Firma"
	(
		"FirmaId" 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


ALTER TABLE "public"."User" 
	ADD CONSTRAINT "FK_d80b91b41e983fdd5d03d541590" FOREIGN KEY
	(
		"FirmaId" 
	)
	REFERENCES "public"."Firma"
	(
		"FirmaId" 
	)
	ON DELETE CASCADE
	ON UPDATE NO ACTION;


